### ISSUE TITLE
Router configuration "override_subgraph_url" is not working in combination with Hive CDN endpoint 

### ISSUE THREAD

**Issue by s-af** [kamilkisiela/graphql-hive#2011]
Hello! 

In my current setup I override subgraph urls using [override_subgraph_url](https://www.apollographql.com/docs/router/configuration/overview/#subgraph-routing-urls) properties in router.yaml configuration file:
```
supergraph:
  listen: 0.0.0.0:4000
override_subgraph_url:
  account: http://my-special-subgraph-url/graphql
```
When I run router docker image (ghcr.io/kamilkisiela/graphql-hive/apollo-router) in combination with env variables HIVE_CDN_KEY + HIVE_CDN_ENDPOINT url overrides ignored. In combination with APOLLO_ROUTER_SUPERGRAPH_PATH or APOLLO_GRAPH_REF + APOLLO_KEY url overrides work as expected.
