### ISSUE TITLE
Hive CLI Github Actions error message

### ISSUE THREAD

**Issue by krisztiansala** [kamilkisiela/graphql-hive#2800]
Using the Hive CLI in Github Actions produces this error message:
```
 ›   Error: command != not found
```

This are the runtime versions: `@graphql-hive/cli/0.29.0 linux-x64 node-v18.17.1` 
Otherwise, the CLI works fine, but this error message pops up each time it is used.

Github Action file to reproduce it: 
```yaml
name: Hive Test

on:
  workflow_dispatch:

jobs:
  setup:
    name: Test
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - run: curl -sSL https://graphql-hive.com/install.sh | sh
      - run: hive --help

```
