### ISSUE TITLE
Client name unknown in Insights

### ISSUE THREAD

**Issue by klys-equinix** [kamilkisiela/graphql-hive#4292]
I am using Apollo Federation 2 setup, with usage reporting using router plugin with default config. 
I am making requests using apollo studio with headers set like
<img width="621" alt="Screenshot 2024-03-20 at 13 14 13" src="https://github.com/kamilkisiela/graphql-hive/assets/20441031/64e6a21d-3829-4986-88d5-112da254ac48">
And i can see in network tab they are being sent
<img width="157" alt="Screenshot 2024-03-20 at 13 14 33" src="https://github.com/kamilkisiela/graphql-hive/assets/20441031/c160ddf2-b13e-41b2-81f7-a8818fdf23d4">

But in Hive insights, i see client name as unknown:

<img width="1715" alt="Screenshot 2024-03-20 at 13 15 28" src="https://github.com/kamilkisiela/graphql-hive/assets/20441031/5aa16066-5d04-4ffd-a2c5-8627bc0b8b26">

**Comment by kamilkisiela** [comment]
Apollo Router <-> Hive integration uses `graphql-client-name` by default.

In order to use a different header name, you can define the values in router configuration:

```yaml
supergraph:
  listen: 0.0.0.0:4000
plugins:
  hive.usage:
    client_name_header: "x-client-name"
    client_version_header: "x-client-version"
```

https://the-guild.dev/graphql/hive/docs/integrations/apollo-router#configuration-1
